export const ADD_TO_CART = "ADD_TO_CART";
export const CART_DETAILS_REQUEST = "CART_DETAILS_REQUEST";
export const CART_DETAILS_SUCCESS = "CART_DETAILS_SUCCESS";
export const CART_DETAILS_FAILURE = "CART_DETAILS_FAILURE";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_ERRORS = "CLEAR_ERRORS";