export const ADD_ORDER_DETAILS = "ADD_ORDER_DETAILS";
export const ORDER_DETAILS_FAILURE ="ORDER_DETAILS_FAILURE";
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";